Movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path, include
from movie import urls
from .views import index, star

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', index),
    # include the other urlconf "movies"
    path('movie/', include('movie.urls')),
    path('star', star)
]

movie/urls.py
from django.urls import path, reverse
from . import views

app_name = 'movie'

urlpatterns = [
    # default index
    path('', views.IndexView.as_view(), name='index'),

    # hot movies
    path('hot', views.PopularMovieView.as_view(), name='hot'),

    # login
    path('login', views.LoginView.as_view(), name='login'),

    # logout
    path('logout', views.UserLogout, name='logout'),

    # register
    path('register', views.RegisterView.as_view(), name='register'),

    # tag check
    path('tag', views.TagView.as_view(), name='tag'),

    # search function
    path('search', views.SearchView.as_view(), name='search'),

    # movie detail
    path('detail/<int:pk>', views.MovieDetailView.as_view(), name='detail'),

    # rate history
    path('history/<int:pk>', views.RatingHistoryView.as_view(),name='history'),

    # detail log
    path('del_rec/<int:pk>', views.delete_recode, name='delete_record'),

    # recommend page
    path('recommend', views.RecommendMovieView.as_view(),name='recommend'),

    # similarity
    # path('calc_movie_similarity',views.calc_movie_similarity,name='calc_similarity')

]

movie/models.py
# It contains the essential fields and behaviors of the data you’re storing.
# Generally, each model maps to a single database table.
from django.db import models
from django.db.models import Avg
from django.core import validators


class Genre(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'Genre'

    def __str__(self):
        return f"<Genre:{self.name}>"


class Movie(models.Model):
    name = models.CharField(max_length=256)
    imdb_id = models.IntegerField()
    time = models.CharField(max_length=256, blank=True)
    genre = models.ManyToManyField(Genre)
    release_time = models.CharField(max_length=256, blank=True)
    intro = models.TextField(blank=True)
    director = models.CharField(max_length=256, blank=True)
    writers = models.CharField(max_length=256, blank=True)
    actors = models.CharField(max_length=512, blank=True)
    # The similarity between movie and movie
    # The similarity of A to B is same with B to A,，so symmetrical should be True
    movie_similarity = models.ManyToManyField("self", through="Movie_similarity", symmetrical=True)

    class Meta:
        db_table = 'Movie'

    def __str__(self):
        return f"<Movie:{self.name},{self.imdb_id}>"

    def get_score(self):
        # define a method to get average score
        # formate {'score__avg': 3.125}
        result_dct = self.movie_rating_set.aggregate(Avg('score'))
        try:
            result = round(result_dct['score__avg'], 1)
        except TypeError:
            return 0
        else:
            return result

    def get_user_score(self, user):
        return self.movie_rating_set.filter(user=user).values('score')

    def get_score_int_range(self):
        return range(int(self.get_score()))

    def get_genre(self):
        genre_dct = self.genre.all().values('name')
        genre_lst = []
        for dct in genre_dct.values():
            genre_lst.append(dct['name'])
        return genre_lst

    def get_similarity(self, k=5):
        # get 5 most similar movies
        similarity_movies = self.movie_similarity.all()[:k]
        print(similarity_movies)
        # movies=Movie.objects.filter(=similarity_movies)
        # print(movies)
        return similarity_movies


class Movie_similarity(models.Model):
    movie_source = models.ForeignKey(Movie, related_name='movie_source', on_delete=models.CASCADE)
    movie_target = models.ForeignKey(Movie, related_name='movie_target', on_delete=models.CASCADE)
    similarity = models.FloatField()

    class Meta:
        # order of similarity by dec
        ordering = ['-similarity']


class User(models.Model):
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    rating_movies = models.ManyToManyField(Movie, through="Movie_rating")

    def __str__(self):
        return "<USER:( name: {:},password: {:},email: {:} )>".format(self.name, self.password, self.email)

    class Meta:
        db_table = 'User'


class Movie_rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, unique=False)
    score = models.FloatField()
    comment = models.TextField(blank=True)

    class Meta:
        db_table = 'Movie_rating'


class Movie_hot(models.Model):
    # top hot 100 movies
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating_number = models.IntegerField()

    class Meta:
        db_table = 'Movie_hot'
        ordering = ['-rating_number']

movie/forms.py
from django import forms
# from django.forms  import ModelForm
from movie.models import User, Movie_rating


class RegisterForm(forms.ModelForm):
    """
    Form used for register
    """
    password_repeat = forms.CharField(max_length=256)

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst

    # Valid password
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        pwd = cleaned_data.get('password')
        password_repeat = cleaned_data.get('password_repeat')
        if pwd != password_repeat:
            raise forms.ValidationError(message='The two passwords entered are inconsistent！')
        return cleaned_data

    class Meta:
        model = User
        fields = ['name', 'password', 'email']


class LoginForm(forms.ModelForm):
    """
    Form used for Login
    """
    name = forms.CharField(max_length=128)
    remember = forms.IntegerField(required=False)

    class Meta:
        model = User
        fields = ['password']

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst


class CommentForm(forms.ModelForm):
    # Check if the score is 0 after form validation is passed
    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        score = cleaned_data.get('score')
        if score == 0:
            raise forms.ValidationError(message='Rating cannot be empty！')
        else:
            return cleaned_data

    class Meta:
        # Movie ratings, only record ratings and reviews
        model = Movie_rating
        fields = ['score', 'comment']

movie/views.py
import csv
import time
import os.path
from math import sqrt
from django.contrib import messages
from django.db.models import Avg, Count, Max
from django.http import HttpResponse, request
from django.shortcuts import render, redirect, reverse
from .forms import RegisterForm, LoginForm, CommentForm
from django.views.generic import View, ListView, DetailView
from .models import User, Movie, Genre, Movie_rating, Movie_similarity, Movie_hot

# DO NOT MAKE ANY CHANGES
BASE = os.path.dirname(os.path.abspath(__file__))


class IndexView(ListView):
    model = Movie
    template_name = 'movie/index.html'
    paginate_by = 15
    context_object_name = 'movies'
    ordering = 'imdb_id'
    page_kwarg = 'p'

    def get_queryset(self):
        # return top 1000 movies
        return Movie.objects.filter(imdb_id__lte=1000)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        # print(context)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


class PopularMovieView(ListView):
    model = Movie_hot
    template_name = 'movie/hot.html'
    paginate_by = 15
    context_object_name = 'movies'
    # ordering = '-movie_hot__rating_number' # no effect
    page_kwarg = 'p'

    def get_queryset(self):
        hot_movies = Movie_hot.objects.all().values("movie_id")
        movies = Movie.objects.filter(id__in=hot_movies).annotate(nums=Max('movie_hot__rating_number')).order_by('-nums')
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PopularMovieView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        # print(context)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


class TagView(ListView):
    model = Movie
    template_name = 'movie/tag.html'
    paginate_by = 15
    context_object_name = 'movies'
    # ordering = 'movie_rating__score'
    page_kwarg = 'p'

    def get_queryset(self):
        if 'genre' not in self.request.GET.dict().keys():
            movies = Movie.objects.all()
            return movies[100:200]
        else:
            movies = Movie.objects.filter(genre__name=self.request.GET.dict()['genre'])
            print(movies)
            return movies[:100]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagView, self).get_context_data(*kwargs)
        if 'genre' in self.request.GET.dict().keys():
            genre = self.request.GET.dict()['genre']
            context.update({'genre': genre})
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


class SearchView(ListView):
    model = Movie
    template_name = 'movie/search.html'
    paginate_by = 15
    context_object_name = 'movies'
    # ordering = 'movie_rating__score'
    page_kwarg = 'p'

    def get_queryset(self):
        movies = Movie.objects.filter(name__icontains=self.request.GET.dict()['keyword'])
        print(movies)
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        # self.genre=self.request.GET.dict()['genre']
        context = super(SearchView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        context.update({'keyword': self.request.GET.dict()['keyword']})
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# register view
class RegisterView(View):
    def get(self, request):
        return render(request, 'movie/register.html')

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            # no error, save it
            form.save()
            return redirect(reverse('movie:index'))
        else:
            # error, relink to register page
            errors = form.get_errors()
            for error in errors:
                messages.info(request, error)
            print(form.errors.get_json_data())
            return redirect(reverse('movie:register'))


# Login View
class LoginView(View):
    def get(self, request):
        return render(request, 'movie/login.html')

    def post(self, request):
        print(request.POST)
        form = LoginForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            pwd = form.cleaned_data.get('password')
            user = User.objects.filter(name=name, password=pwd).first()
            # username = form.cleaned_data.get('name')
            # print(username)
            # pwd = form.cleaned_data.get('password')
            if user:
                request.session['user_id'] = user.id
                return redirect(reverse('movie:index'))
            else:
                print('invalid user name or error password!')
                messages.info(request, 'invalid user name or error password!')
                return redirect(reverse('movie:login'))
        else:
            print("error in form!!!")
            errors = form.get_errors()
            for error in errors:
                messages.info(request, error)
            print(form.errors.get_json_data())
            return redirect(reverse('movie:login'))


def UserLogout(request):
    # logout and stop session
    request.session.set_expiry(-1)
    return redirect(reverse('movie:index'))


class MovieDetailView(DetailView):
    model = Movie
    template_name = 'movie/detail.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        # add rating score paremeter
        context = super().get_context_data(**kwargs)
        # check whether login
        login = True
        try:
            user_id = self.request.session['user_id']
        except KeyError as e:
            login = False

        # get movie's primary key
        pk = self.kwargs['pk']

templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'movie/favicon1.ico' %}"/>
    <link rel="bookmark" href="{% static 'movie/favicon1.ico' %}"/>
    <meta charset="UTF-8">
    <title>Movie</title>

    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script><!--引入jQuery-->
    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>


</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movie:index' %}">Homepage</a>
        </div>
        <!--
        TODO:

        -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'movie:hot' %}">Popular</a></li>
                <li>
                    <a href="{% url 'movie:tag' %}">Classification</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" method="GET" action="{% url 'movie:search' %}">
                <div class="form-group">
                    <input type="search" name="keyword" class="form-control" placeholder="Search" required>
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if movie_user %}
                    <li>
                        <!-- Split button -->
                        <div class="btn-group" style="margin-top:8px">
                            <button type="button" class="btn btn-info">
                                <a href="{% url 'movie:history' movie_user.id %}" style="text-decoration: none;color:inherit">
                                    History</a></button>
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'movie:recommend' %}">Recommended List</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'movie:logout' %}">Log out</a></li>
                            </ul>
                        </div>
                    </li>
                {% else %}
                    {#                If not log in, show these two links#}
                    <li><a href="{% url 'movie:register' %}">Register</a></li>
                    <li><a href="{% url 'movie:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block content %}

{% endblock %}
</body>
</html>

templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block content %}

    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
    <link href="{% static 'css/star-rating.css' %}" media="all" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/star-rating.js' %}" type="text/javascript"></script>
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            max-width: 800px;
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
        }
        .smovie{
            display: block;
            float: left;
            font-size: 15px;
            text-align: center;
            margin:0 25px 10px 0;
            width: 200px;
        }
        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <!--展示电影信息-->
    <div class="container">
        <div class="poster">
            <a href="{% url 'movie:detail' movie.pk %}" class="item">
                <div class="poster_div">
                    <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                </div>
            </a>
        </div>
        <div class="info">
            <p>
                Movie Name：
                {{ movie.name }}
                <span>
                    {% for foo in movie.get_score_int_range %}
                        ❤
                    {% endfor %}
                </span>
                <strong style="color:#e09015">{{ movie.get_score }}</strong>
            </p>
            <p>Introduction：{{ movie.intro }}</p>
            <p>Director：{{ movie.director }}</p>
            <p>Playwright：{{ movie.writers }}</p>
            <p>Actors：{{ movie.actors }}</p>
            <p>
                Type：
                {% for genre in movie.get_genre %}
                    <a href="{% url 'movie:tag' %}?genre={{ genre }}">{{ genre }}</a>
                    {% if not forloop.last %}
                        <span>|</span>
                    {% endif %}
                {% endfor %}
            </p>
            <p>Duration Time：{{ movie.time }}</p>
            <p>Release Time：{{ movie.release_time }}</p>
        </div>
    </div>

    <div class="container similarity_movie">
        <br>
        <div class="alert alert-warning" role="alert">People who like this movie also like...</div>

        {% for movie in similarity_movies %}
            <div class="smovie" {% if forloop.first %} style="margin-left: -6px" {% endif %}>
                <a href="{% url 'movie:detail' movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                        <p>{{ movie.name }}
                            <strong style="color:#e09015">{{ movie.get_score }}</strong>
                        </p>
                    </div>
                </a>
            </div>

        {% endfor %}

    </div>

    <div class="container">
        <br>
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
    {% if login %}

        <div class="container">

            <hr>
            <form class="star" action="" method="post">
                <input id="input-2ba" name="score" value="{{ score }}" type="number" class="rating" min="0" max="5"
                       step="0.5"
                       data-stars=5
                       data-symbol="&#xe005;" data-default-caption="{rating} hearts" data-star-captions="{}">
                <label for="comment">Comments:</label>
                <textarea class="form-control" name="comment" rows="5" id="comment">{{ comment }}</textarea>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" style="margin-right: 10px">Submit</button>
                    <button type="reset" class="btn btn-default">Clear</button>
                </div>
            </form>
            <br>
            <script>
                jQuery(document).ready(function () {
                    $(".rating-kv").rating();
                });
            </script>
        </div>

    {% endif %}

{% endblock %}

templates/movie/history.html
{% extends 'movie/base.html' %}
{% block content %}
    <script src="{% static 'layer/layer.js' %}"></script>
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
        }

        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
        <div class="alert-success alert" role="alert">Rating History</div>
    </div>

    {% for rating in ratings %}
        <div class="container">
            <div class="poster">
                <a href="{% url 'movie:detail' rating.movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ rating.movie.imdb_id }}.jpg" alt="">
                    </div>
                </a>
            </div>
            <div class="info">
                <p>
                    Movie Name：
                    {{ rating.movie.name }}
                    <span>
                    {% for foo in rating.movie.get_score_int_range %}
                        ❤
                    {% endfor %}
                    </span>
                    <strong style="color:#e09015">{{ rating.movie.get_score }}</strong>
                </p>
                <p>
                    My rating:
                    <strong style="color:#e09015">{{ rating.score }} </strong>
                    My comments:
                    <strong>{{ rating.comment }}</strong>
                </p>
                {#                <a href="#">#}
                <button type="button" class="btn btn-warning"
                        onclick="confirm_delete('{% url "movie:delete_record" rating.movie.id %}')"><span
                        class="glyphicon glyphicon-trash"></span>delete comments
                </button>
                {#                </a>#}
            </div>

        </div>
        <div class="container"><hr></div>

    {% endfor %}
    <script>
        // Function to delete an article
        function confirm_delete(url) {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "confirm deletion",
                // 正文
                content: "Are you sure to delete this comment？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    // 指定应当前往的 url
                    {#location.href='{% url "article:article_delete" article.id %}'#}
                    {#location.href = '{% url "movie:delete_record" %}'#}
                    location.href = url
                },
            })
        }
    </script>
    <script>
        window.onkeyup = function (ev) {
            var key = ev.keyCode || ev.which;
            if (key == 27) { //按下Escape
                layer.closeAll(); //疯狂模式，关闭所有层
            }
        }
    </script>
{% endblock %}

templates/movie/hot.html
{% extends 'movie/base.html' %}
{% block content %}
    <style>
        .item {
            display: block;
            float: left;
            font-size: 15px;
            text-align: center;
            margin: 0 25px 10px 0;
            width: 200px;
        }

        .item .poster_div {
            height: 320px;
            overflow: hidden;
        }
    </style>
    <div class="container">
        {% for movie in movies %}
            <a href="{% url 'movie:detail' movie.pk %}" class="item">
                <div class="poster_div">
                    <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                    <p>{{ movie.name }}
                        <strong style="color:#e09015">{{ movie.get_score }}</strong>
                    </p>
                </div>
            </a>
        {% endfor %}
    </div>

    <nav style="text-align: center;">
        <ul class="pagination">
            {#previous page#}
            {% if page_obj.has_previous %}
                <li><a href="{% url 'movie:hot' %}?p={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
            {% endif %}

            {% if left_has_more %}
                <li><a href="{% url 'movie:hot' %}?p=1">1</a></li>
                <li><a href="javascript:void(0)">...</a></li>
            {% endif %}

            {% for left_page in left_pages %}
                <li><a href="{% url 'movie:hot' %}?p={{ left_page }}">{{ left_page }}</a></li>
            {% endfor %}

            <li class="active"><a href="javascript:void(0);">{{ current_page }}</a></li>

            {% for right_page in right_pages %}
                <li><a href="{% url 'movie:hot' %}?p={{ right_page }}">{{ right_page }}</a></li>
            {% endfor %}
            {% if right_has_more %}
                <li><a href="javascript:void(0)">...</a></li>
                <li><a href="{% url 'movie:hot' %}?p={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% endif %}
            {#next page#}
            {% if page_obj.has_next %}
                <li><a href="{% url 'movie:hot' %}?p={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0);">Previous</a></li>
            {% endif %}
        </ul>
    </nav>

{% endblock %}