Movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path, include
from movie import urls
from .views import index, star

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', index),
    # include the other urlconf "movies"
    path('movie/', include('movie.urls')),
    path('star', star)
]

movie/urls.py
from django.urls import path, reverse
from . import views

app_name = 'movie'

urlpatterns = [
    # default index
    path('', views.IndexView.as_view(), name='index'),

    # hot movies
    path('hot', views.PopularMovieView.as_view(), name='hot'),

    # login
    path('login', views.LoginView.as_view(), name='login'),

    # logout
    path('logout', views.UserLogout, name='logout'),

    # register
    path('register', views.RegisterView.as_view(), name='register'),

    # tag check
    path('tag', views.TagView.as_view(), name='tag'),

    # search function
    path('search', views.SearchView.as_view(), name='search'),

    # movie detail
    path('detail/<int:pk>', views.MovieDetailView.as_view(), name='detail'),

    # rate history
    path('history/<int:pk>', views.RatingHistoryView.as_view(),name='history'),

    # detail log
    path('del_rec/<int:pk>', views.delete_recode, name='delete_record'),

    # recommend page
    path('recommend', views.RecommendMovieView.as_view(),name='recommend'),

    # similarity
    # path('calc_movie_similarity',views.calc_movie_similarity,name='calc_similarity')

]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>

    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <style>
        /*
         * Globals
         */

        /* Links */
        a,
        a:focus,
        a:hover {
            color: #fff;
        }

        /* Custom default button */
        .btn-default,
        .btn-default:hover,
        .btn-default:focus {
            color: #333;
            text-shadow: none; /* Prevent inheritance from `body` */
            background-color: #fff;
            border: 1px solid #fff;
        }


        /*
         * Base structure
         */

        html,
        body {
            height: 100%;
            background-color: #333;
        }

        body {
            color: #fff;
            text-align: center;
            text-shadow: 0 1px 3px rgba(0, 0, 0, .5);
        }

        /* Extra markup and styles for table-esque vertical and horizontal centering */
        .site-wrapper {
            display: table;
            width: 100%;
            height: 100%; /* For at least Firefox */
            min-height: 100%;
            -webkit-box-shadow: inset 0 0 100px rgba(0, 0, 0, .5);
            box-shadow: inset 0 0 100px rgba(0, 0, 0, .5);
        }

        .site-wrapper-inner {
            display: table-cell;
            vertical-align: top;
        }

        .cover-container {
            margin-right: auto;
            margin-left: auto;
        }

        /* Padding for spacing */
        .inner {
            padding: 30px;
        }


        /*
         * Header
         */
        .masthead-brand {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .masthead-nav > li {
            display: inline-block;
        }

        .masthead-nav > li + li {
            margin-left: 20px;
        }

        .masthead-nav > li > a {
            padding-right: 0;
            padding-left: 0;
            font-size: 16px;
            font-weight: bold;
            color: #fff; /* IE8 proofing */
            color: rgba(255, 255, 255, .75);
            border-bottom: 2px solid transparent;
        }

        .masthead-nav > li > a:hover,
        .masthead-nav > li > a:focus {
            background-color: transparent;
            border-bottom-color: #a9a9a9;
            border-bottom-color: rgba(211, 169, 169, 0.25);
        }

        .masthead-nav > .active > a,
        .masthead-nav > .active > a:hover,
        .masthead-nav > .active > a:focus {
            color: #fff;
            border-bottom-color: #fff;
        }

        @media (min-width: 768px) {
            .masthead-brand {
                float: left;
            }

            .masthead-nav {
                float: right;
            }
        }


        /*
         * Cover
         */

        .cover {
            padding: 0 20px;
        }

        .cover .btn-lg {
            padding: 10px 20px;
            font-weight: bold;
        }


        /*
         * Footer
         */

        .mastfoot {
            color: #999; /* IE8 proofing */
            color: rgba(255, 255, 255, .5);
        }


        /*
         * Affix and center
         */

        @media (min-width: 768px) {
            /* Pull out the header and footer */
            .masthead {
                position: fixed;
                top: 0;
            }

            .mastfoot {
                position: fixed;
                bottom: 0;
            }

            /* Start the vertical centering */
            .site-wrapper-inner {
                vertical-align: middle;
            }

            /* Handle the widths */
            .masthead,
            .mastfoot,
            .cover-container {
                width: 100%; /* Must be percentage or pixels for horizontal alignment */
            }
        }

        @media (min-width: 992px) {
            .masthead,
            .mastfoot,
            .cover-container {
                width: 700px;
            }
        }

    </style>
</head>

<body>
<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <div class="masthead clearfix">
                <div class="inner">
{#                    <img src="static/movie/sdsc_logo.svg" align="left", width="80%">#}
{#                    <h3 class="masthead-brand">front page</h3>#}
{#                    <nav>#}
{#                        <ul class="nav masthead-nav">#}
{#                            <li class="active"><a href="#">Movie recommendation system</a></li>#}
{#                            <li><a href="#">Features</a></li>#}
{#                            <li><a href="#">Contact</a></li>#}
{#                        </ul>#}
{#                    </nav>#}

                </div>
            </div>

            <div class="inner cover">
                <h2 class="cover-heading">Movie Website and Recommendation System</h2>
                <br/> <br/>
                <p class="lead">Build with Django+Mysql+Bootstrap</p>
                <br/>
                <p class="lead">
                    <a href="{% url 'movie:index' %}" class="btn btn-lg btn-default">Enter the Homepage</a>
                </p>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>Project for SDSC 5003, by Group Atom </p>
                </div>
            </div>

        </div>

    </div>

</div>

</body>
</html>